name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" # otomatis setiap hari 00:00 UTC (07:00 WIB)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output folder
        run: mkdir -p output

      - name: Download GitHub Stats
        run: |
          curl -o output/github-stats.svg "https://github-readme-stats.vercel.app/api?username=rilfikri15&show_icons=true&theme=tokyonight&count_private=true"
          curl -o output/top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=rilfikri15&layout=compact&theme=tokyonight"
          curl -o output/trophies.svg "https://github-profile-trophy.vercel.app/?username=rilfikri15&theme=tokyonight&no-frame=true&margin-w=15"

      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "Updated GitHub stats [skip ci]" || echo "No changes to commit"
          git push
